//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_GUITARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Client
    {
        public int idClient { get; set; }
        public string Nom { get; set; }
        public string Adresse { get; set; }
        public string telephone { get; set; }
    }
}
