//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_GUITARE
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Guitare
    {
        public int idGuitare { get; set; }
        public Nullable<System.DateTime> dateCommande { get; set; }
        public int idEtatCommande { get; set; }
        public Nullable<int> idMicro { get; set; }
        public Nullable<int> idMicro_1 { get; set; }
        public int idBois { get; set; }
        public int idBois_1 { get; set; }
        public Nullable<int> idClient { get; set; }
        public int idBois_2 { get; set; }
        public int idVibrato { get; set; }
        public int idMicro_2 { get; set; }
    }
}
